### ISSUE TITLE
Tank difficulty 

### ISSUE THREAD

**Issue by TheAddis** [PlaceholderGames/TankGame#11]
If we have time we could do varying tank difficulty
Easy - 100% movement speed and 100% shooting speed
Medium - 150% movement speed and 150% shooting speed
Hard - 200% movement speed and 200% shooting speed

**Comment by SharktasticA** [comment]
I reckon I could do the speed of projectiles in the time we have. I'll explore that today.

**Comment by TheAddis** [comment]
![tank model base easy](https://cloud.githubusercontent.com/assets/22661594/19765945/142d8c4c-9c43-11e6-9989-c4048ce576ed.png)
![tank model turret easy](https://cloud.githubusercontent.com/assets/22661594/19765946/157b8fc2-9c43-11e6-9e00-392e2a5ea69c.png)

Easy tank model turret and base

**Comment by TheAddis** [comment]
![tank model base medium](https://cloud.githubusercontent.com/assets/22661594/19765993/4bac6846-9c43-11e6-987f-969ac23390e8.png)
![tank model turret medium](https://cloud.githubusercontent.com/assets/22661594/19765996/54ab40fc-9c43-11e6-8d39-4ce4aa9b4a6e.png)

Medium tanks base and turret

**Comment by TheAddis** [comment]
![tank model base hard](https://cloud.githubusercontent.com/assets/22661594/19766023/764b5a08-9c43-11e6-913a-86ca117d1958.png)
![tank model turret hard](https://cloud.githubusercontent.com/assets/22661594/19766026/781831d0-9c43-11e6-9a77-53e3aa01b8fd.png)

Hard Tanks base and turret

**Comment by SharktasticA** [comment]
Acknowledged.

**Comment by SharktasticA** [comment]
Completed as part of enemy tank designed.
