### ISSUE TITLE
Sounds for Tanks and Explosions

### ISSUE THREAD

**Issue by Etheren** [PlaceholderGames/TankGame#15]
Included are 2 sounds for tanks when they are on screen and when they die. Each are in each zip file, and are ready to be imported into stencyl. If anything comes up, shout and I'll re-do them in Audacity. If this concerns you, assign yourself to it.

[Tank Explosion.zip](https://github.com/PlaceholderGames/TankGame/files/555737/Tank.Explosion.zip)
[Tank Moving.zip](https://github.com/PlaceholderGames/TankGame/files/555739/Tank.Moving.zip)

**Comment by SharktasticA** [comment]
Assigned myself as I will be implementing the tank explosion sound as part of my task. 

Thanks for sending these!

**Comment by SharktasticA** [comment]
All used.
