### ISSUE TITLE
Collision on maps

### ISSUE THREAD

**Issue by SharktasticA** [PlaceholderGames/TankGame#16]
The maps lack collision detectors, thus the tanks and other objects go straight through the walls within the maps. This will need to implemented before I can move forward with making the projectile collide with the walls.

**Comment by Callum2497** [comment]
@SharktallicA [Tank Game.zip](https://github.com/PlaceholderGames/TankGame/files/568981/Tank.Game.zip)
This game has the Maps with Collisions included (Tested with a Tank on map)

**Comment by SharktasticA** [comment]
Acknowledged. Thanks.
