### ISSUE TITLE
AI for Enemy Tanks (Movement)

### ISSUE THREAD

**Issue by SharktasticA** [PlaceholderGames/TankGame#18]
Implement mechanism to enable logical movement for enemy tank.

Must include:
- four- or eight-directional movement
- boundary detection
- suitable animations

Due: 3rd November 2016, by end of the day

**Comment by TheAddis** [comment]
Will be done by the end of Thursday

**Comment by SharktasticA** [comment]
Completed with the project for the attacking issue for AI.
