### ISSUE TITLE
AI for Enemy Tanks (Attacking)

### ISSUE THREAD

**Issue by SharktasticA** [PlaceholderGames/TankGame#19]
Implement mechanism to enable target acquistion and firing from enemy tank.

Must include:
- ability to lock onto the player
- ability to fire at the player when they are not hidden behind cover

Due: 3rd November 2016, by end of the day

**Comment by bead789** [comment]
We have finished with the AI without shooting each other 
[tanks (2).zip](https://github.com/PlaceholderGames/TankGame/files/568941/tanks.2.zip)

**Comment by SharktasticA** [comment]
Acknowledged. Will be merged with the other projects shortly.
