### ISSUE TITLE
Create level designs for first three levels

### ISSUE THREAD

**Issue by SharktasticA** [PlaceholderGames/TankGame#2]
Create three level designs for the basic starting levels of the game. 

Must include:
- Each design increases in complexity
- Provide unique challenges

Due: 20th October 2016, by end of day

**Comment by Callum2497** [comment]
This Zip File includes the 3 maps for the Tank Game.
[Tank Game.zip](https://github.com/PlaceholderGames/TankGame/files/541851/Tank.Game.zip)

**Comment by SharktasticA** [comment]
Task completion acknowledged.
