### ISSUE TITLE
Finished Project File Thread

### ISSUE THREAD

**Issue by SharktasticA** [PlaceholderGames/TankGame#20]
This thread will be for uploading the finished .stencyl file for our project. I want this to be here by the end of the day (3rd November) so we all can have the finished file ready for tomorrow.

I understand that a few of the game's components are spread out between a few local projects as of now. I recommend we all upload our mutual project files once the features we are working on individually are completed so we can combine them sometime in the day to make our finished project file.

**Comment by Etheren** [comment]
This is my stuff. The collision in the levels doesn't really work, and you'll just need to remove the placeholder buttons on the levels.

[game.zip](https://github.com/PlaceholderGames/TankGame/files/568903/game.zip)

**Comment by SharktasticA** [comment]
Thanks! I am working to combine the code from that, movement & enemies project and my ballistics project to produce a finished game within the day. The project with levels and map (submitted by Callum G.) will be the basis project that will serve as the complete game. After a group talk, it is agreed that people who respectively helped with contributing a specific part of the game will aid me when combining their part of the project.

**Comment by SharktasticA** [comment]
**Progress report**
All projects have now been merged. There are a few issues to resolve (like incorrectly-spawning bullets and collisions), but they will be sorted ASAP.

**Comment by SharktasticA** [comment]
**Progress report**
Uploading this project so that Callum G. can change the placeholder back buttons and level selects.
[BattleTanks.zip](https://github.com/PlaceholderGames/TankGame/files/570276/BattleTanks.zip)

**Comment by SharktallicA** [comment]
Three level screenshots for Callum
![1](https://cloud.githubusercontent.com/assets/22660310/19989028/ae9daba8-a21b-11e6-9c2f-2212136b42da.PNG)
![2](https://cloud.githubusercontent.com/assets/22660310/19989030/aeabb1f8-a21b-11e6-89fb-10de7c9ce739.PNG)
![3](https://cloud.githubusercontent.com/assets/22660310/19989029/ae9f1790-a21b-11e6-9c43-0da92f585966.PNG)

**Comment by Etheren** [comment]
Updated the Levels and the Back buttons.

[GameFiles.zip](https://github.com/PlaceholderGames/TankGame/files/570297/GameFiles.zip)

**Comment by SharktasticA** [comment]
Final game project. As good as we are going to get.

[BattleTanks.zip](https://github.com/PlaceholderGames/TankGame/files/571050/BattleTanks.zip)
