### ISSUE TITLE
Player character design

### ISSUE THREAD

**Issue by SharktasticA** [PlaceholderGames/TankGame#4]
Create a design for the player-operated tank.

Must include:
- Inspired by German Tiger II tank
- Seperated images for tank body and turret
- Images must be transparent

Due: 13th October 2016

**Comment by SharktasticA** [comment]
Player tank has been completed before issue was created.

**Comment by SharktasticA** [comment]
Issue reopened and conversation reopened to allow uploading of tank design.

**Comment by TheAddis** [comment]
Sorry I sent them to this last week but it's disappeared? I will re upload them all tomorrow since I can't access them here

**Comment by SharktasticA** [comment]
Okay. No worries. Brad has an e-mailed copy to work with at the moment if I am not mistaken?

**Comment by TheAddis** [comment]
![tank turret](https://cloud.githubusercontent.com/assets/22661594/19765880/b52069ea-9c42-11e6-9fc5-c9868c46a3ee.png)

**Comment by TheAddis** [comment]
[tank model base 2.zip](https://github.com/PlaceholderGames/TankGame/files/555641/tank.model.base.2.zip)

**Comment by TheAddis** [comment]
This is the model split from into Turret and Base

**Comment by SharktasticA** [comment]
Acknowledged. Issue closed.

**Comment by TheAddis** [comment]
[tank model base 2.zip](https://github.com/PlaceholderGames/TankGame/files/555689/tank.model.base.2.zip)
[Tank turret.zip](https://github.com/PlaceholderGames/TankGame/files/555690/Tank.turret.zip)

apparently it failed to send

**Comment by SharktasticA** [comment]
Okie dokie.
