### ISSUE TITLE
Create explosion effect

### ISSUE THREAD

**Issue by SharktasticA** [PlaceholderGames/TankGame#5]
Create an explosion effect that displays when the player (and enemy tanks) explode.

Must include:
- three stages of the effect (Ben)
- sound to be triggered by explosion happens (Callum)

Due: 20th October 2016, by end of day

**Comment by Etheren** [comment]
Here's a sound effect for when the tank explodes and that. See if you can add it.

[New Compressed (zipped) Folder.zip](https://github.com/PlaceholderGames/TankGame/files/541540/New.Compressed.zipped.Folder.zip)

**Comment by TheAddis** [comment]
![explosion](https://cloud.githubusercontent.com/assets/22661594/19558472/a4e8a946-96c2-11e6-83fc-067bb18dcb2a.png)
![explosion 2](https://cloud.githubusercontent.com/assets/22661594/19558480/aa979bb8-96c2-11e6-93e7-ab58471411a7.png)
![explosion 3](https://cloud.githubusercontent.com/assets/22661594/19558482/aef6569a-96c2-11e6-995a-d58b2bb496f2.png)
3 stage explosion done

**Comment by SharktasticA** [comment]
Tasks have been completed. Issue closed.
