### ISSUE TITLE
Enemy character design

### ISSUE THREAD

**Issue by SharktasticA** [PlaceholderGames/TankGame#6]
Create a design for the enemy-operated tank.

Must include:
- Similar design to player tank, but different colour scheme
- Seperated images for tank body and turret
- Images must be transparent
- Three different sizes to represent threat level of enemy; light, medium and heavy (optional if time allows)

Due: 27th October 2016, by end of day

**Comment by TheAddis** [comment]
Again will be uploaded tomorrow when I have access to it

**Comment by TheAddis** [comment]
Instead of sizes we could do different colours like 
Green - easy
Yellow - medium
Red - hard

**Comment by SharktasticA** [comment]
I like that idea. What ever you think you can implement the fastest due to time constraints.

**Comment by SharktasticA** [comment]
Completed.
