### ISSUE TITLE
Game menu screen

### ISSUE THREAD

**Issue by SharktasticA** [PlaceholderGames/TankGame#7]
Create a menu screen.

Must include:
- Buttons for; Quick Play, Level Select, Credits (Callum G.)
- Relevant still background image of gameplay or of level design (Callum F.)

Due: 27th October 2016, by end of day

**Comment by Callum2497** [comment]
[Stencyl Maps Screenshots.zip](https://github.com/PlaceholderGames/TankGame/files/555578/Stencyl.Maps.Screenshots.zip)

These are the screenshots of the 3 maps we are using.

**Comment by Etheren** [comment]
I'll need the actual levels, so I am able to have the menu load directly into them

**Comment by Etheren** [comment]
Here are the menus and the Levels in the ZIP :)
[BattleTanks.zip](https://github.com/PlaceholderGames/TankGame/files/556902/BattleTanks.zip)

**Comment by SharktasticA** [comment]
Acknowledged.

**Comment by SharktasticA** [comment]
NOTE: To everyone, since this contains the menu and the levels, this project will be the one that all code is imported to from our separate projects.
