### ISSUE TITLE
Projectile design

### ISSUE THREAD

**Issue by SharktasticA** [PlaceholderGames/TankGame#9]
Create a design for the projectile fired by tanks.

Must include:
- assuming tank is sized at 30px, the bullet needs to roughly match the size of the turret barrel at that size
- must be visuallly-identifiable given the size and the backgrounds of the level design.

Due: 24th October 2016, by end of day

**Comment by TheAddis** [comment]
![shell](https://cloud.githubusercontent.com/assets/22661594/19766806/b780b5dc-9c47-11e6-9eac-053951ef4790.png)

Simple but shrunk down it should work

**Comment by SharktasticA** [comment]
That's fine.
